all:
  children:
    fortigates:
      hosts:
        fortigate01:
          ansible_host: "{{ lookup('env', 'FORTIGATE_HOST') }}"
          ansible_connection: httpapi
          ansible_network_os: fortinet.fortios.fortios
          ansible_httpapi_use_ssl: true
          ansible_httpapi_validate_certs: "{{ (lookup('env', 'FORTIGATE_VALIDATE_CERTS') | default('false', true)) | bool }}"
          ansible_httpapi_port: 443
          fortigate_vdom: "{{ lookup('env', 'FORTIGATE_VDOM') | default('root', true) }}"
          fortigate_api_token: "{{ lookup('env', 'FORTIGATE_API_TOKEN') }}"