---
- name: Modify the lab service object
  hosts: fortigates
  gather_facts: false
  vars_files:
    - ../vars/lab.yml
  roles:
    - role: fortigate_service
      service_state: present
      service_port: "{{ test_service.modified_tcp_portrange }}"
